/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#1b1b24',
        'outline-variant': '#c7c4d8',
        'error-container': '#ffdad6',
        'secondary-fixed': '#acedff',
        'surface-variant': '#e4e1ee',
        'secondary-fixed-dim': '#4cd7f6',
        'tertiary-container': '#a44100',
        'secondary-container': '#57dffe',
        outline: '#777587',
        'on-surface-variant': '#464555',
        'surface-container-high': '#eae6f4',
        secondary: '#00687a',
        'primary-fixed-dim': '#c3c0ff',
        'on-error-container': '#93000a',
        'on-secondary-container': '#006172',
        'tertiary-fixed': '#ffdbcc',
        'surface-container-highest': '#e4e1ee',
        'on-primary-container': '#dad7ff',
        'surface-container': '#f0ecf9',
        'surface-bright': '#fcf8ff',
        'primary-container': '#4f46e5',
        background: '#fcf8ff',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'inverse-surface': '#302f39',
        tertiary: '#7e3000',
        'surface-container-low': '#f5f2ff',
        'primary-fixed': '#e2dfff',
        surface: '#fcf8ff',
        primary: '#3525cd',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '280px',
        'container-padding': '24px',
        gutter: '16px',
        'card-padding': '20px',
      },
      fontFamily: {
        'body-sm': ['Inter'],
        'display-lg': ['Inter'],
        'display-lg-mobile': ['Inter'],
        'headline-md': ['Inter'],
        'body-md': ['Inter'],
        'label-caps': ['Inter'],
        'title-sm': ['Inter'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'display-lg-mobile': [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};